/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package numerical.recipes;

import org.junit.Test;

import static org.junit.Assert.*;

public class MatrixTest {

    @Test
    public void testMatrixConstructorEmpty() {
        Matrix matrix = new Matrix();
        double[][] expected = new double[0][0];
        assertArrayEquals(matrix.array, expected);
    }

    @Test
    public void testMatrixConstructorSingleValueNaN() {
        Matrix matrix = new Matrix(1, 1);
        double[][] expected = {{Double.NaN}};
        assertArrayEquals(matrix.array, expected);
    }

    @Test
    public void testMatrixConstructorSingleValueOne() {
        Matrix matrix = new Matrix(1, 1, 1);
        double[][] expected = {{1}};
        assertArrayEquals(matrix.array, expected);
    }
    //----------------------------------------Method testing------------------------------------------------------------
    @Test
    public void testMatrixAdd() throws Exception {
        Matrix A = new Matrix(1, 1, 1);
        Matrix B = new Matrix(1, 1, 1);
        Matrix C = new Matrix(1, 1, 2);
        assertArrayEquals(A.add(B).array,C.array);
    }

    @Test
    public void testMatrixAddException() throws Exception {
        Matrix A = new Matrix(2, 1, 1);
        Matrix B = new Matrix(1, 1, 1);
        Exception thrown = assertThrows(Exception.class, () -> A.add(B));
        assertEquals("Dimensions are not equal", thrown.getMessage());
    }

}
